Distro: ubuntu
DE: budgie
# distro-version:
# de-version:
Install:
  Prescript:
    # - hidpi-scale-fix.sh
    # - openssh-config
  Packages:
    - xfce4-terminal
    - gnome-tweaks
    - guake
    - gnome-system-monitor
    - xdotool
    - git
    - vim
    - zsh
    - dconf-editor
    - neofetch
    - hardinfo
    - screen
    - locate
    - autojump
    - gir1.2-gtksource-4                # nemo-preview dependency
    - nemo-preview
    - sublime-text
    - code
    - ncdu
    - htop
    - tmux
    - remmina
    - freerdp2-x11
    - font-manager
    - budgie-calendar-applet
    - budgie-hotcorners-applet
    - budgie-workspace-overview-applet
    - budgie-applications-menu-applet
    - budgie-appmenu-applet
    - budgie-indicator-applet
    - budgie-dropby-applet
    - budgie-network-manager-applet
    - budgie-takeabreak-applet
    - budgie-performance-gauge-applet
    - xserver-xorg-input-synaptics
    # - virtualbox
    # - virtualbox-ext-pack
  Snaps:
  Flatpacks:
  Postscript:
    - printer-fix
    - mojave
    - ubuntu-budgie-defaults
    - kinto
    - git-projects
    - touchpad-gnome-reverse
    - battery-gnome-percentage
    - time-12hr-gnome
    # - homebrew
    - autojump                  # Configures bash & zsh to source it
    - homerc-files
    - terminal-zsh-defaults
    - git-config
    # - libinput-gestures
    # - hidpi-laptop-budgie
  # Done: echo "Congrats";
  #   echo "You are done!"
Remove:
  Packages:
